packages:
  - "packages/components/*"
  - "packages/core/*"
  - "packages/utils/*"
  - "packages/tools/*"
  - "packages/docs/contributorsGuide"

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.3
  "@types/react-dom": ^18.3.0
  react-aria: ^3.34.1
  "@types/node": ^22.5.5
  "typescript": "^5.6.0"
  "eslint": "^9.11.1"
  "@eslint/js": "^9.11.1"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-jest": "^28.8.3"
