name: Add Chore Task
description: Adds a new task for a chore
title: "[Chore]: "
labels:
  - "chore"
  - "Status:Ready"
projects:
  - "MotionWindUI/3"
assignees:
  - Kyle-Gagnon-99
body:
  - type: markdown
    attributes:
      value: |
        ### 🧹 Add a New Chore Task

        Please provide the necessary details to add a new chore task to the project.

  - type: textarea
    id: description
    attributes:
      label: 📝 What is the chore?
      description: Please describe the chore in detail.
      placeholder: |
        e.g., Refactor the components to adhere to new format.
        Specific tasks:
        - Update component A
        - Modify styling in component B
        - Ensure consistency across all affected files

  - type: dropdown
    id: area
    attributes:
      label: 📂 Which area?
      description: Select the area of the project/monorepo that this chore targets.
      multiple: true
      options:
        - components
        - core
        - utils
        - hooks
        - docs
