name: Add Fix Task
description: Adds a new task to fix a bug
title: "[Fix]: "
labels:
  - "fix"
projects:
  - "MotionWindUI/2"
assignees:
  - Kyle-Gagnon-99
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the information below to add a new bug fix task
  - type: textarea
    id: description
    attributes:
      label: What does it fix?
      description: What does this task aim to fix? What is the issue number?
      placeholder: |
        This task fixes...

        1. Closes #(Issue Number)
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Information
      description: Any extra information about this bug/fix? (Any ideas?)
